### ISSUE TITLE
Meta issue for new feature/plan

### ISSUE THREAD

**Issue by wiiznokes** [wiiznokes/cosmic-clipboard-manager#10]
- [ ] change the database to use diese (or [not](https://www.github.com/spacejam/sled/issues/1444)) (with a SQL backend probably) is it suitable for image ?
- [ ] add a global shortcut (ctrl + v), probably need d-bus, but S76 folks should know (actually, need the global shortcut from portal, but its not currently impl in cosmic)
- [x] add quick settings dropdown when right click the icon
- [x] add a settings window to remove the clear button and store future settings (winit + applet is not a things atm)
- [x] add a dropdown menu on right click of entries to remove the "remove" ugly button (it would be nice if we could use the one from iced_aw, but it doesn't work for now)
- [ ] support image, and maybe other mime type #9 
- [x] search should works with accents
- [ ] auto remove old entries
